### PR TITLE
Ensure no parameter is passed to 'done' function

### PR DESCRIPTION
**Pull request by landru29**
Since nodejs 9.0.0, fs.writeFile seems to throw an undefined parameter as error instead of no parameter in the call back. It leads to an error 'done is not a function'

Now working with node 10.0.0

### CODE REVIEW

**Comment by landru29** [comment]
@sapegin  Any chance on getting this merged and a new release please?

**Comment by sapegin** [comment]
I can give you push rights to the repo and an npm package, if you want to make a new release. I haven't touched Grunt and icon fonts for many years ;-/

**Comment by landru29** [comment]
Yes, that's a solution !
